# Generated by Django 3.1.5 on 2021-04-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_titel', models.CharField(max_length=50)),
                ('pro_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('pro_description', models.CharField(max_length=100)),
                ('pro_images', models.ImageField(upload_to='pro_images')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_category')),
            ],
        ),
    ]
