# Generated by Django 3.1.5 on 2021-04-27 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_product_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='emal',
            new_name='email',
        ),
    ]
